version: '2.2'

services:
  tomcat:
    image: beleza-app
    build: .
    ports:
      - '8081:8080'
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    volumes: 
      - ./target/beleza-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/beleza.war
    networks:
      - mt-network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=belezadb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3307:3306'
    networks:
      - mt-network
  

volumes:
  mysql-data:
    driver: local
networks:
  mt-network:
    driver: bridge
