spring:
  datasource:
    url: jdbc:mysql://localhost:3306/belezadb
    username: root
    password: super123
    platform: mysql
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://mysql:3306/belezadb
    username: root
    password: root
    platform: mysql
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect